kumuluzee:
  name: adresse-data-gouv-api-microprofile
  version: 1.0-SNAPSHOT
  env:
    name: dev
  server:
    http:
      port: 6060
      proxy-forwarding: true
  metrics:
    web-instrumentation:
      - name: testEndpoint
        url-pattern: data/hello/*
  opentracing:
    jaeger:
      service-name: adresse-data-gouv # if not set kumuluzee.name value is used
      agent-host: ${env.JAEGER_HOST:localhost} # default agent host
      agent-port: ${env.JAEGER_PORT:5775} # default agent port
      reporter:
        log-spans: true
        max-queue-size: 3
#      tags: key1=val1, key2=val2
      sampler:
        type: const # default sampler type
        param: 1 # default sampler param

#        type: probabilistic
 #       param: 0.1 => 10% des requêtes

#        manager-host-port: http://localhost:5775
      propagation: B3
#      traceid-128bit: true
url:
  api:
    adresse:
      base:
        nationale: https://api-adresse.data.gouv.fr/
use:
  proxy:
    pole-emploi: true

mp:
  opentracing:
    server:
      skip-pattern: /health|/metrics|/openapi
