kumuluzee:
  name: adresse-data-gouv-api-microprofile
  version: 1.0-SNAPSHOT
  env:
    name: dev
  metrics:
    web-instrumentation:
      - name: testEndpoint
        url-pattern: data/hello/*
  opentracing:
    jaeger:
      service-name: adresse-data-gouv # if not set kumuluzee.name value is used
      agent-host: localhost # default agent host
      agent-port: 5775 # default agent port
      reporter:
        log-spans: true
        max-queue-size: 3
#      tags: key1=val1, key2=val2
      sampler:
        type: const # default sampler type
        param: 1 # default sampler param
#        manager-host-port: http://localhost:5775
      propagation: B3
#      traceid-128bit: tru
url:
  api:
    adresse:
      base:
        nationale: https://api-adresse.data.gouv.fr/
mp:
  opentracing:
    server:
      skip-pattern: /health|/metrics|/openapi
